apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: {{ .Values.names.clusterRoleName }}
  labels:
    name: {{ .Values.names.clusterRoleName }}
  # "namespace" omitted since ClusterRoles are not namespaced
rules:
- apiGroups:
  - ""
  resources: [
    "pods",
    "services",
    "nodes",
    "nodes/proxy",
    "serviceaccounts",
    "namespaces",
    "resourcequotas",
    "daemonsets",
    "deployments",
    "replicasets",
    "statefulsets",
    "networkpolicies",
    "ingresses",
    "podsecuritypolicies",
    "roles",
    "rolebindings",
    "clusterroles",
    "clusterrolebindings",
    "cronjobs",
    "secrets",
    "configmaps"
  ]
  verbs: [get, list]
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources: [
    "pods",
    "services",
    "nodes",
    "nodes/proxy",
    "serviceaccounts",
    "namespaces",
    "resourcequotas",
    "daemonsets",
    "deployments",
    "replicasets",
    "statefulsets",
    "networkpolicies",
    "ingresses",
    "podsecuritypolicies",
    "roles",
    "rolebindings",
    "clusterroles",
    "clusterrolebindings",
    "cronjobs",
    "secrets",
    "configmaps"
  ]
  verbs: [get, list]
- apiGroups:
  - extensions
  resources: [
    "pods",
    "services",
    "nodes",
    "nodes/proxy",
    "serviceaccounts",
    "namespaces",
    "resourcequotas",
    "daemonsets",
    "deployments",
    "replicasets",
    "statefulsets",
    "networkpolicies",
    "ingresses",
    "podsecuritypolicies",
    "roles",
    "rolebindings",
    "clusterroles",
    "clusterrolebindings",
    "cronjobs",
    "secrets",
    "configmaps"
  ]
  verbs: [get, list]
- apiGroups:
  - apps
  resources: [
    "pods",
    "services",
    "nodes",
    "nodes/proxy",
    "serviceaccounts",
    "namespaces",
    "resourcequotas",
    "daemonsets",
    "deployments",
    "replicasets",
    "statefulsets",
    "networkpolicies",
    "ingresses",
    "podsecuritypolicies",
    "roles",
    "rolebindings",
    "clusterroles",
    "clusterrolebindings",
    "cronjobs",
    "secrets",
    "configmaps"
  ]
  verbs: [get, list]
# [TODO] need to split ClusterRole to 'get' and 'list' so it would be forbidden, for example - to allow listing secrets and no allow getting secrets values.